---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: golang
    tag: 1

inputs:
- name: information-site
- name: version
  optional: true

outputs:
- name: assets

run:
  path: information-site/ci/build
